//
//  StudentLocation.swift
//  On The Map
//
//  Created by Ali Mir on 10/22/16.
//  Copyright © 2016 com.AliMir. All rights reserved.
//

//Key: objectId
//Description: an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
//Parse Type: String
//Example Value: 8ZExGR5uX8

//Key: uniqueKey
//Description: an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
//Parse Type: String
//Example Value: 1234

//Key: firstName
//Description: the first name of the student which matches their Udacity profile first name
//Parse Type: String
//Example Value: John

//Key: lastName
//Description: the last name of the student which matches their Udacity profile last name
//Parse Type: String
//Example Value: Doe

//Key: mapString
//Description: the location string used for geocoding the student location
//Parse Type: String
//Example Value: Mountain View, CA

//Key: mediaURL
//Description: the URL provided by the student
//Parse Type: String
//Example Value: https://udacity.com

//Key: latitude
//Description: the latitude of the student location (ranges from -90 to 90)
//Parse Type: Number
//Example Value: 37.386052

//Key: longitude
//Description: the longitude of the student location (ranges from -180 to 180)
//Parse Type: Number
//Example Value: -122.083851

import Foundation

struct StudentLocation {
    // MARK: Properties
    let objectID: String
    let uniqueKey: String
    let firstName: String
    let lastName: String
    let mapString: String
    let latitude: Double
    let longitude: Double
    let mediaURL: String
    
    // construct a TMDBMovie from a dictionary
    init(dictionary: [String : AnyObject]) {
        self.objectID = dictionary[ParseClient.JSONResponseKeys.StudentObjectID] as! String
        self.uniqueKey = dictionary[ParseClient.JSONResponseKeys.StudentUniqueKey] as!  String
        self.firstName = dictionary[ParseClient.JSONResponseKeys.StudentFirstName] as! String
        self.lastName = dictionary[ParseClient.JSONResponseKeys.StudentLastName] as! String
        self.mapString = dictionary[ParseClient.JSONResponseKeys.StudentMapString] as! String
        self.latitude = dictionary[ParseClient.JSONResponseKeys.StudentLatitude] as! Double
        self.longitude = dictionary[ParseClient.JSONResponseKeys.StudentLongitude] as! Double
        self.mediaURL = dictionary[ParseClient.JSONResponseKeys.StudentMediaURL] as! String
    }
    
    static func studentLocationsFromResults(results: [[String : AnyObject]]) -> [StudentLocation] {
        var students = [StudentLocation]()

        // iterate through array of dictionaries, each StudentLocation is a dictionary
        for result in results {
            students.append(StudentLocation(dictionary: result))
        }
        
        return students
    }
}






